### ISSUE TITLE
起動しない

### ISSUE THREAD

**Issue by plonk** [fusuya/mogevader#1]
`img/` ディレクトリがなくて、画像やフォントのアセットにアクセスできないため、タイトル画面まで進みませんでした。

![Screenshot from 2020-07-19 20-38-42](https://user-images.githubusercontent.com/1680210/87873883-22bf6200-ca00-11ea-8d6b-fb39d8c4090d.png)

**Comment by fusuya** [comment]
アップロード完了！

**Comment by plonk** [comment]
ありがとう遊べました！
